# Uncomment this line to define a global platform for your project
platform :ios, '8.0'



target 'ProjectFrameworkDemo' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for ProjectFrameworkDemo
    pod 'SDCycleScrollView','~> 1.66'
    pod 'YYCache'
    pod 'XLsn0wKit'
    
    pod 'MLTransition', '~> 2.1.2'#滑动返回
    
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'
#   精简版和完整版区别:
#   正常的分享、登录功能，精简版和完整版是没有任何区别的，分享及登录界面也没有任何区别，因此，我们推荐开发者们可以直接使用精简版来进行集成，可以大幅度缩减体积

#    # 集成微信(完整版14.4M)
#    pod 'UMengUShare/Social/WeChat'
#    # 集成QQ/QZone/TIM(完整版7.6M)
#    pod 'UMengUShare/Social/QQ'
#    # 集成新浪微博(完整版25.3M)
#    pod 'UMengUShare/Social/Sina'

    # 集成微信(精简版0.2M)
    pod 'UMengUShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMengUShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMengUShare/Social/ReducedSina'


end
